version: "3.7"

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    privileged: true
    networks:
      ats_net:
        ipv4_address: 172.25.0.6

  phpfpm:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./tmp/grinds:/tmp/grinds
    ports:
      - "9006:9000"
    privileged: true
    networks:
      ats_net:
        ipv4_address: 172.25.0.2
    environment:
      XDEBUG_CONFIG: client_host=${IP}
      DEBUG: 1
    working_dir: /var/www


  mysql56:
    image: mysql:5.7.35
    restart: unless-stopped
    container_name: mysql56-container
    ports:
      - "3303:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ./mysql57-data:/var/lib/mysql
      - ./mysql57-files:/var/lib/mysql-files
    privileged: true
    networks:
      ats_net:
        ipv4_address: 172.25.0.3

networks:
  ats_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
